#!/bin/bash
verification_tools=`gawk '/verification_tools/ { $1 = ""; $2 = ""; print $0; }' Makefile.tools`
for i in $verification_tools; do echo "$i:"; ./verify_$i -k 100 -T 100000 -t 100 -s 0; done
